// Generated from the ExactCup Ingredient Density Dataset (CC BY 4.0, https://exactcup.github.io/).
// Grams of one US customary cup per ingredient. Do not edit by hand.
extension IngredientDensityCatalog {
    static let rows: [IngredientDensity] = [
        IngredientDensity(slug: "all-purpose-flour", name: "All-Purpose Flour", category: "Flours & Starches", gramsPerCup: 120, aliases: ["plain flour", "ap flour"]),
        IngredientDensity(slug: "bread-flour", name: "Bread Flour", category: "Flours & Starches", gramsPerCup: 120, aliases: ["strong flour"]),
        IngredientDensity(slug: "cake-flour", name: "Cake Flour", category: "Flours & Starches", gramsPerCup: 120, aliases: []),
        IngredientDensity(slug: "whole-wheat-flour", name: "Whole Wheat Flour", category: "Flours & Starches", gramsPerCup: 113, aliases: ["wholemeal flour"]),
        IngredientDensity(slug: "self-rising-flour", name: "Self-Rising Flour", category: "Flours & Starches", gramsPerCup: 113, aliases: ["self raising flour"]),
        IngredientDensity(slug: "almond-flour", name: "Almond Flour", category: "Flours & Starches", gramsPerCup: 96, aliases: ["ground almonds", "almond meal"]),
        IngredientDensity(slug: "cornstarch", name: "Cornstarch", category: "Flours & Starches", gramsPerCup: 112, aliases: ["corn flour", "cornflour"]),
        IngredientDensity(slug: "cocoa-powder", name: "Cocoa Powder", category: "Flours & Starches", gramsPerCup: 85, aliases: ["unsweetened cocoa"]),
        IngredientDensity(slug: "granulated-sugar", name: "Granulated Sugar", category: "Sugars & Syrups", gramsPerCup: 200, aliases: ["white sugar", "caster sugar"]),
        IngredientDensity(slug: "brown-sugar", name: "Brown Sugar (packed)", category: "Sugars & Syrups", gramsPerCup: 213, aliases: ["light brown sugar", "dark brown sugar"]),
        IngredientDensity(slug: "powdered-sugar", name: "Powdered Sugar", category: "Sugars & Syrups", gramsPerCup: 113, aliases: ["confectioners sugar", "icing sugar"]),
        IngredientDensity(slug: "honey", name: "Honey", category: "Sugars & Syrups", gramsPerCup: 340, aliases: []),
        IngredientDensity(slug: "maple-syrup", name: "Maple Syrup", category: "Sugars & Syrups", gramsPerCup: 322, aliases: []),
        IngredientDensity(slug: "corn-syrup", name: "Corn Syrup", category: "Sugars & Syrups", gramsPerCup: 328, aliases: []),
        IngredientDensity(slug: "butter", name: "Butter", category: "Dairy & Fats", gramsPerCup: 227, aliases: []),
        IngredientDensity(slug: "milk", name: "Milk", category: "Dairy & Fats", gramsPerCup: 240, aliases: ["whole milk"]),
        IngredientDensity(slug: "heavy-cream", name: "Heavy Cream", category: "Dairy & Fats", gramsPerCup: 232, aliases: ["double cream", "whipping cream"]),
        IngredientDensity(slug: "sour-cream", name: "Sour Cream", category: "Dairy & Fats", gramsPerCup: 230, aliases: []),
        IngredientDensity(slug: "cream-cheese", name: "Cream Cheese", category: "Dairy & Fats", gramsPerCup: 232, aliases: []),
        IngredientDensity(slug: "yogurt", name: "Yogurt", category: "Dairy & Fats", gramsPerCup: 245, aliases: ["yoghurt", "greek yogurt"]),
        IngredientDensity(slug: "vegetable-oil", name: "Vegetable Oil", category: "Dairy & Fats", gramsPerCup: 218, aliases: ["canola oil"]),
        IngredientDensity(slug: "olive-oil", name: "Olive Oil", category: "Dairy & Fats", gramsPerCup: 216, aliases: []),
        IngredientDensity(slug: "coconut-oil", name: "Coconut Oil", category: "Dairy & Fats", gramsPerCup: 218, aliases: []),
        IngredientDensity(slug: "peanut-butter", name: "Peanut Butter", category: "Dairy & Fats", gramsPerCup: 256, aliases: []),
        IngredientDensity(slug: "chocolate-chips", name: "Chocolate Chips", category: "Baking Ingredients", gramsPerCup: 170, aliases: ["choc chips"]),
        IngredientDensity(slug: "shredded-coconut", name: "Shredded Coconut", category: "Baking Ingredients", gramsPerCup: 80, aliases: ["desiccated coconut"]),
        IngredientDensity(slug: "raisins", name: "Raisins", category: "Baking Ingredients", gramsPerCup: 145, aliases: []),
        IngredientDensity(slug: "chopped-nuts", name: "Chopped Nuts", category: "Baking Ingredients", gramsPerCup: 120, aliases: ["walnuts", "pecans"]),
        IngredientDensity(slug: "rolled-oats", name: "Rolled Oats", category: "Grains & Misc", gramsPerCup: 90, aliases: ["old fashioned oats"]),
        IngredientDensity(slug: "white-rice", name: "White Rice (uncooked)", category: "Grains & Misc", gramsPerCup: 185, aliases: ["long grain rice"]),
        IngredientDensity(slug: "quinoa", name: "Quinoa (uncooked)", category: "Grains & Misc", gramsPerCup: 170, aliases: []),
        IngredientDensity(slug: "cornmeal", name: "Cornmeal", category: "Grains & Misc", gramsPerCup: 122, aliases: ["polenta"]),
        IngredientDensity(slug: "breadcrumbs", name: "Breadcrumbs (dry)", category: "Grains & Misc", gramsPerCup: 108, aliases: []),
        IngredientDensity(slug: "water", name: "Water", category: "Grains & Misc", gramsPerCup: 237, aliases: []),
        IngredientDensity(slug: "salt", name: "Table Salt", category: "Grains & Misc", gramsPerCup: 273, aliases: []),
        IngredientDensity(slug: "caster-sugar", name: "Caster Sugar", category: "Sugars & Syrups", gramsPerCup: 190, aliases: ["superfine sugar", "baker's special sugar", "castor sugar"]),
        IngredientDensity(slug: "coconut-sugar", name: "Coconut Sugar", category: "Sugars & Syrups", gramsPerCup: 154, aliases: ["coconut palm sugar", "coco sugar"]),
        IngredientDensity(slug: "molasses", name: "Molasses", category: "Sugars & Syrups", gramsPerCup: 340, aliases: ["black treacle"]),
        IngredientDensity(slug: "golden-syrup", name: "Golden Syrup", category: "Sugars & Syrups", gramsPerCup: 340, aliases: ["light treacle", "cane syrup"]),
        IngredientDensity(slug: "agave-nectar", name: "Agave Nectar", category: "Sugars & Syrups", gramsPerCup: 336, aliases: ["agave syrup"]),
        IngredientDensity(slug: "pitted-dates-chopped", name: "Pitted Dates (Chopped)", category: "Sugars & Syrups", gramsPerCup: 149, aliases: ["chopped dates", "pitted dates"]),
        IngredientDensity(slug: "dried-cranberries", name: "Dried Cranberries", category: "Sugars & Syrups", gramsPerCup: 114, aliases: ["craisins", "sweetened dried cranberries"]),
        IngredientDensity(slug: "sweetened-condensed-milk", name: "Sweetened Condensed Milk", category: "Dairy & Fats", gramsPerCup: 306, aliases: ["condensed milk"]),
        IngredientDensity(slug: "evaporated-milk", name: "Evaporated Milk", category: "Dairy & Fats", gramsPerCup: 226, aliases: ["unsweetened condensed milk"]),
        IngredientDensity(slug: "buttermilk", name: "Buttermilk", category: "Dairy & Fats", gramsPerCup: 227, aliases: ["cultured buttermilk"]),
        IngredientDensity(slug: "ricotta-cheese", name: "Ricotta Cheese", category: "Dairy & Fats", gramsPerCup: 227, aliases: ["ricotta"]),
        IngredientDensity(slug: "mascarpone", name: "Mascarpone", category: "Dairy & Fats", gramsPerCup: 227, aliases: ["mascarpone cheese", "italian cream cheese"]),
        IngredientDensity(slug: "cottage-cheese", name: "Cottage Cheese", category: "Dairy & Fats", gramsPerCup: 226, aliases: ["curd cheese"]),
        IngredientDensity(slug: "grated-parmesan", name: "Grated Parmesan", category: "Dairy & Fats", gramsPerCup: 100, aliases: ["grated parmigiano", "parmesan cheese"]),
        IngredientDensity(slug: "shredded-cheddar", name: "Shredded Cheddar", category: "Dairy & Fats", gramsPerCup: 113, aliases: ["grated cheddar", "cheddar cheese"]),
        IngredientDensity(slug: "shredded-mozzarella", name: "Shredded Mozzarella", category: "Dairy & Fats", gramsPerCup: 113, aliases: ["grated mozzarella", "mozzarella cheese"]),
        IngredientDensity(slug: "pumpkin-puree", name: "Pumpkin Puree", category: "Dairy & Fats", gramsPerCup: 227, aliases: ["pumpkin purée", "canned pumpkin"]),
        IngredientDensity(slug: "applesauce", name: "Applesauce", category: "Dairy & Fats", gramsPerCup: 255, aliases: ["apple sauce", "apple puree"]),
        IngredientDensity(slug: "mashed-banana", name: "Mashed Banana", category: "Dairy & Fats", gramsPerCup: 227, aliases: ["banana puree"]),
        IngredientDensity(slug: "rye-flour", name: "Rye Flour", category: "Flours & Starches", gramsPerCup: 106, aliases: ["dark rye flour", "whole rye flour"]),
        IngredientDensity(slug: "oat-flour", name: "Oat Flour", category: "Flours & Starches", gramsPerCup: 92, aliases: ["ground oats"]),
        IngredientDensity(slug: "coconut-flour", name: "Coconut Flour", category: "Flours & Starches", gramsPerCup: 128, aliases: []),
        IngredientDensity(slug: "semolina", name: "Semolina", category: "Flours & Starches", gramsPerCup: 163, aliases: ["semolina flour", "durum semolina"]),
        IngredientDensity(slug: "tapioca-flour", name: "Tapioca Flour", category: "Flours & Starches", gramsPerCup: 113, aliases: ["tapioca starch"]),
        IngredientDensity(slug: "arrowroot-powder", name: "Arrowroot Powder", category: "Flours & Starches", gramsPerCup: 128, aliases: ["arrowroot flour", "arrowroot starch"]),
        IngredientDensity(slug: "pecan-halves", name: "Pecan Halves", category: "Baking Ingredients", gramsPerCup: 105, aliases: ["pecans"]),
        IngredientDensity(slug: "whole-almonds", name: "Whole Almonds", category: "Baking Ingredients", gramsPerCup: 142, aliases: ["almonds"]),
        IngredientDensity(slug: "sesame-seeds", name: "Sesame Seeds", category: "Baking Ingredients", gramsPerCup: 142, aliases: ["sesame"]),
        IngredientDensity(slug: "chia-seeds", name: "Chia Seeds", category: "Baking Ingredients", gramsPerCup: 148, aliases: ["chia"]),
        IngredientDensity(slug: "ground-flaxseed", name: "Ground Flaxseed", category: "Baking Ingredients", gramsPerCup: 100, aliases: ["flax meal", "ground flax", "milled flaxseed", "flaxseed meal"]),
        IngredientDensity(slug: "poppy-seeds", name: "Poppy Seeds", category: "Baking Ingredients", gramsPerCup: 144, aliases: ["poppyseed"]),
        IngredientDensity(slug: "panko-breadcrumbs", name: "Panko Breadcrumbs", category: "Grains & Misc", gramsPerCup: 50, aliases: ["panko", "japanese breadcrumbs"]),
        IngredientDensity(slug: "steel-cut-oats", name: "Steel-Cut Oats", category: "Grains & Misc", gramsPerCup: 140, aliases: ["pinhead oats", "irish oats"]),
        IngredientDensity(slug: "couscous-dry", name: "Couscous (Dry)", category: "Grains & Misc", gramsPerCup: 175, aliases: ["dry couscous"]),
        IngredientDensity(slug: "bulgur-dry", name: "Bulgur (Dry)", category: "Grains & Misc", gramsPerCup: 140, aliases: ["dry bulgur", "bulgur wheat", "cracked wheat"]),
        IngredientDensity(slug: "pearl-barley", name: "Pearl Barley (Dry)", category: "Grains & Misc", gramsPerCup: 213, aliases: ["pearled barley", "dry barley"]),
        IngredientDensity(slug: "vegetable-shortening", name: "Vegetable Shortening", category: "Dairy & Fats", gramsPerCup: 184, aliases: ["shortening", "crisco"]),
        IngredientDensity(slug: "tahini", name: "Tahini", category: "Dairy & Fats", gramsPerCup: 256, aliases: ["sesame paste", "tahini paste"]),
        IngredientDensity(slug: "almond-butter", name: "Almond Butter", category: "Dairy & Fats", gramsPerCup: 272, aliases: ["almond nut butter"]),
        IngredientDensity(slug: "white-chocolate-chips", name: "White Chocolate Chips", category: "Baking Ingredients", gramsPerCup: 170, aliases: ["white choc chips", "white chocolate morsels"]),
        IngredientDensity(slug: "walnuts-chopped", name: "Walnuts (Chopped)", category: "Baking Ingredients", gramsPerCup: 113, aliases: ["walnuts", "chopped walnuts"]),
        IngredientDensity(slug: "graham-cracker-crumbs", name: "Graham Cracker Crumbs", category: "Grains & Misc", gramsPerCup: 100, aliases: ["graham crumbs", "crushed graham crackers"]),
        IngredientDensity(slug: "hazelnuts", name: "Hazelnuts (Whole)", category: "Baking Ingredients", gramsPerCup: 142, aliases: ["filberts", "whole hazelnuts"]),
        IngredientDensity(slug: "cashews", name: "Cashews (Whole)", category: "Baking Ingredients", gramsPerCup: 113, aliases: ["whole cashews", "cashew nuts"]),
        IngredientDensity(slug: "pine-nuts", name: "Pine Nuts", category: "Baking Ingredients", gramsPerCup: 142, aliases: ["pignoli", "pinoli"]),
    ]
}
